// this files handles all the weapons of vanilla arma 
// this files handles all the weapons of vanilla arma 

//class CfgVehicles
//{
	class Weapon_arifle_MX_khk_F: Weapon_Base_F { scope = 0; };	
	class arifle_MX_Base_F: Rifle_Base_F { scope = 0; };
	class arifle_Katiba_Base_F: Rifle_Base_F { scope = 0; };
	class LMG_Mk200_F: Rifle_Long_Base_F { scope = 0; };
	class arifle_MX_SW_F: arifle_MX_Base_F { scope = 0; };
	class mk20_base_F: Rifle_Base_F { scope = 0; };
	class Tavor_base_F: Rifle_Base_F { scope = 0; };
	class DMR_03_base_F: Rifle_Long_Base_F { scope = 0; };
	class DMR_06_base_F: Rifle_Long_Base_F { scope = 0; };
	class EBR_base_F: Rifle_Long_Base_F { scope = 0; };
	class DMR_01_base_F: Rifle_Long_Base_F { scope = 0; };
	class arifle_MX_Black_F;
	class arifle_MX_khk_F: arifle_MX_Black_F { scope = 0; };
	class arifle_MX_khk_ACO_Pointer_F: arifle_MX_khk_F { scope = 0; };
	class arifle_MX_khk_Holo_Pointer_F: arifle_MX_khk_F { scope = 0; };
	class arifle_MX_khk_Hamr_Pointer_F: arifle_MX_khk_F { scope = 0; };
	class arifle_MX_khk_Hamr_Pointer_Snds_F: arifle_MX_khk_F { scope = 0; };
	class arifle_MX_khk_Pointer_F: arifle_MX_khk_F { scope = 0; };
	class arifle_MX_khk_ACO_Pointer_Snds_F: arifle_MX_khk_F { scope = 0; };
	class arifle_MX_GL_Black_F;
	class arifle_MX_GL_khk_F: arifle_MX_GL_Black_F { scope = 0; };
	class arifle_MX_GL_khk_ACO_F: arifle_MX_GL_khk_F { scope = 0; };
	class arifle_MX_GL_khk_Hamr_Pointer_F: arifle_MX_GL_khk_F { scope = 0; };
	class arifle_MX_GL_khk_Holo_Pointer_Snds_F: arifle_MX_GL_khk_F { scope = 0; };
	class arifle_MX_SW_Black_F;
	class arifle_MX_SW_khk_F: arifle_MX_SW_Black_F { scope = 0; };
	class arifle_MX_SW_khk_Pointer_F: arifle_MX_SW_khk_F { scope = 0; };
	class arifle_MXC_Black_F;
	class arifle_MXC_khk_F: arifle_MXC_Black_F { scope = 0; };
	class arifle_MXC_khk_Holo_Pointer_F: arifle_MXC_khk_F { scope = 0; };
	class arifle_MXC_khk_ACO_F: arifle_MXC_khk_F { scope = 0; };
	class arifle_MXC_khk_ACO_Pointer_Snds_F: arifle_MXC_khk_F { scope = 0; };
	class arifle_MXM_Black_F;
	class arifle_MXM_khk_F: arifle_MXM_Black_F { scope = 0; };
	class arifle_MXM_khk_MOS_Pointer_Bipod_F: arifle_MXM_khk_F { scope = 0; };
	class arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F: arifle_MXM_khk_F { scope = 0; };
	class srifle_LRR_camo_F;
	class srifle_LRR_tna_F: srifle_LRR_camo_F { scope = 0; };
	class srifle_LRR_tna_LRPS_F: srifle_LRR_tna_F { scope = 0; };
	class srifle_GM6_F;
	class srifle_GM6_ghex_F: srifle_GM6_F { scope = 0; };
	class srifle_GM6_ghex_LRPS_F: srifle_GM6_ghex_F { scope = 0; };
	class hgun_P07_F;
	class hgun_P07_khk_F: hgun_P07_F { scope = 0; };
	class hgun_P07_khk_Snds_F: hgun_P07_khk_F { scope = 0; };
	class SMG_02_base_F: Rifle_Short_Base_F { scope = 0; };
	class muzzle_snds_H;
	class muzzle_snds_H_khk_F: muzzle_snds_H { scope = 0; };
	class muzzle_snds_H_snd_F: muzzle_snds_H { scope = 0; };
	class muzzle_snds_M;
	class muzzle_snds_m_khk_F: muzzle_snds_M { scope = 0; };
	class muzzle_snds_m_snd_F: muzzle_snds_M { scope = 0; };
	class muzzle_snds_58_blk_F: muzzle_snds_M { scope = 0; };
	class muzzle_snds_58_wdm_F: muzzle_snds_58_blk_F { scope = 0; };
	class muzzle_snds_58_ghex_F: muzzle_snds_58_wdm_F { scope = 0; };
	class muzzle_snds_58_hex_F: muzzle_snds_58_blk_F { scope = 0; };
	class muzzle_snds_B;
	class muzzle_snds_B_khk_F: muzzle_snds_B { scope = 0; };
	class muzzle_snds_B_snd_F: muzzle_snds_B { scope = 0; };
	class muzzle_snds_65_TI_blk_F: muzzle_snds_M { scope = 0; };
	class muzzle_snds_65_TI_hex_F: muzzle_snds_65_TI_blk_F { scope = 0; };
	class muzzle_snds_65_TI_ghex_F: muzzle_snds_65_TI_blk_F { scope = 0; };
	class muzzle_snds_H_MG;
	class muzzle_snds_H_MG_blk_F: muzzle_snds_H_MG { scope = 0; };
	class muzzle_snds_H_MG_khk_F: muzzle_snds_H_MG { scope = 0; };

	class optic_Arco: ItemCore { scope = 0; };
	class optic_Arco_blk_F: optic_Arco { scope = 0; };
	class optic_Arco_ghex_F: optic_Arco { scope = 0; };
	class optic_DMS;
	class optic_DMS_ghex_F: optic_DMS { scope = 0; };
	class optic_Hamr: ItemCore { scope = 0; };
	class optic_Hamr_khk_F: optic_Hamr { scope = 0; };
	class optic_ERCO_blk_F: optic_Arco { scope = 0; };
	class optic_ERCO_khk_F: optic_ERCO_blk_F { scope = 0; };
	class optic_ERCO_snd_F: optic_ERCO_blk_F { scope = 0; };
	class optic_SOS;
	class optic_SOS_khk_F: optic_SOS { scope = 0; };
	class optic_LRPS;
	class optic_LRPS_tna_F: optic_LRPS { scope = 0; };
	class optic_LRPS_ghex_F: optic_LRPS { scope = 0; };
	class optic_Holosight;
	class optic_Holosight_blk_F: optic_Holosight { scope = 0; };
	class optic_Holosight_khk_F: optic_Holosight { scope = 0; };
	class optic_Holosight_smg;
	class optic_Holosight_smg_blk_F: optic_Holosight_smg { scope = 0; };
	class optic_Holosight_smg_khk_F: optic_Holosight_smg { scope = 0; };
	class bipod_01_F_snd;
	class bipod_01_F_khk: bipod_01_F_snd { scope = 0; };