// this file extracted from bohemia files
//			class PointerSlot: PointerSlot{};

class CfgPatches 
{
			class eurof_BI_equipment_patch
			{
						requiredaddons[] = { "A3_Data_F", "A3_UI_F", "A3_Anims_F", "A3_Anims_F_Config_Sdr", "A3_Weapons_F", "A3_Weapons_F_Acc", "A3_Sounds_F_Mark" };
						units[] = {"B_Assault_Diver","B_AssaultPack_Base","B_AssaultPack_blk","B_AssaultPack_blk_DiverExp","B_AssaultPack_cbr","B_AssaultPack_dgtl","B_AssaultPack_Kerry","B_AssaultPack_khk","B_AssaultPack_mcamo","B_AssaultPack_mcamo_AA","B_AssaultPack_mcamo_AAR","B_AssaultPack_mcamo_Ammo","B_AssaultPack_mcamo_AT","B_AssaultPack_ocamo","B_AssaultPack_rgr","B_AssaultPack_rgr_LAT","B_AssaultPack_rgr_Medic","B_AssaultPack_rgr_ReconExp","B_AssaultPack_rgr_ReconLAT","B_AssaultPack_rgr_ReconMedic","B_AssaultPack_rgr_Repair","B_AssaultPack_sgg","B_AssaultPackG","B_Bergen_Base","B_Bergen_blk","B_Bergen_mcamo","B_Bergen_rgr","B_Bergen_sgg","B_BergenC_Base","B_BergenC_blu","B_BergenC_grn","B_BergenC_red","B_BergenG","B_BergenG_TEST_B_Soldier_overloaded","B_Carryall_Base","B_Carryall_cbr","B_Carryall_cbr_AAT","B_Carryall_khk","B_Carryall_mcamo","B_Carryall_mcamo_AAA","B_Carryall_mcamo_AAT","B_Carryall_ocamo","B_Carryall_ocamo_AAA","B_Carryall_ocamo_AAR","B_Carryall_ocamo_Eng","B_Carryall_ocamo_Exp","B_Carryall_oli","B_Carryall_oucamo","B_Carryall_oucamo_AAA","B_Carryall_oucamo_AAR","B_Carryall_oucamo_AAT","B_Carryall_oucamo_Eng","B_Carryall_oucamo_Exp","B_FieldPack_Base","B_FieldPack_blk","B_FieldPack_blk_DiverExp","B_FieldPack_cbr","B_FieldPack_cbr_AA","B_FieldPack_cbr_AAA","B_FieldPack_cbr_AAT","B_FieldPack_cbr_Ammo","B_FieldPack_cbr_AT","B_FieldPack_cbr_LAT","B_FieldPack_cbr_Medic","B_FieldPack_cbr_Repair","B_FieldPack_cbr_RPG_AT","B_FieldPack_khk","B_FieldPack_ocamo","B_FieldPack_ocamo_AA","B_FieldPack_ocamo_AAR","B_FieldPack_ocamo_Medic","B_FieldPack_ocamo_ReconExp","B_FieldPack_ocamo_ReconMedic","B_FieldPack_oli","B_FieldPack_oucamo","B_FieldPack_oucamo_AA","B_FieldPack_oucamo_AAR","B_FieldPack_oucamo_Ammo","B_FieldPack_oucamo_AT","B_FieldPack_oucamo_LAT","B_FieldPack_oucamo_Medic","B_FieldPack_oucamo_Repair","B_HuntingBackpack","B_Kitbag_Base","B_Kitbag_cbr","B_Kitbag_mcamo","B_Kitbag_mcamo_Eng","B_Kitbag_rgr","B_Kitbag_rgr_AAR","B_Kitbag_rgr_Exp","B_Kitbag_sgg","B_OutdoorPack_Base","B_OutdoorPack_blk","B_OutdoorPack_blu","B_OutdoorPack_tan","B_Parachute","B_supplyCrate_F","B_TacticalPack_Base","B_TacticalPack_blk","B_TacticalPack_mcamo","B_TacticalPack_ocamo","B_TacticalPack_oli","B_TacticalPack_oli_AAR","B_TacticalPack_rgr","Bag_Base","Box_Ammo_F","Box_East_Ammo_F","Box_East_AmmoOrd_F","Box_East_AmmoVeh_F","Box_East_Grenades_F","Box_East_Support_F","Box_East_Wps_F","Box_East_WpsLaunch_F","Box_East_WpsSpecial_F","Box_IND_Ammo_F","Box_IND_AmmoOrd_F","Box_IND_AmmoVeh_F","Box_IND_Grenades_F","Box_IND_Support_F","Box_IND_Wps_F","Box_IND_WpsLaunch_F","Box_IND_WpsSpecial_F","Box_NATO_Ammo_F","Box_NATO_AmmoOrd_F","Box_NATO_AmmoVeh_F","Box_NATO_Grenades_F","Box_NATO_Support_F","Box_NATO_Wps_F","Box_NATO_WpsLaunch_F","Box_NATO_WpsSpecial_F","Box_Wps_F","C_Bergen_Base","C_Bergen_blu","C_Bergen_grn","C_Bergen_red","C_supplyCrate_F","G_AssaultPack","G_Bergen","G_Carryall_Ammo","G_Carryall_Exp","G_FieldPack_LAT","G_FieldPack_Medic","G_TacticalPack_Eng","GroundWeaponHolder","GroundWeaponHolder_Scripted","I_Assault_Diver","I_Carryall_oli_AAA","I_Carryall_oli_AAT","I_Carryall_oli_Eng","I_Carryall_oli_Exp","I_Fieldpack_oli_AA","I_Fieldpack_oli_AAR","I_Fieldpack_oli_Ammo","I_Fieldpack_oli_AT","I_Fieldpack_oli_LAT","I_Fieldpack_oli_Medic","I_Fieldpack_oli_Repair","I_supplyCrate_F","IG_supplyCrate_F","Land_Box_AmmoOld_F","O_Assault_Diver","O_supplyCrate_F","ReammoBox_F","WeaponHolderSimulated","WeaponHolderSimulated_Scripted"};
						weapons[] = 
						{			
						
// BI weapon_f list:

"autocannon_30mm","autocannon_30mm_CTWS","autocannon_35mm","autocannon_40mm_CTWS","autocannon_Base_F","BikeHorn","Binocular","Bomb_03_Plane_CAS_02_F","Bomb_04_Plane_CAS_01_F","cannon_105mm","cannon_120mm","cannon_120mm_long","cannon_125mm","Cannon_30mm_Plane_CAS_02_F","CarHorn","CMFlareLauncher","CMFlareLauncher_Singles","CMFlareLauncher_Triples","FakeHorn","FlareLauncher","gatling_20mm","gatling_25mm","gatling_30mm","Gatling_30mm_Plane_CAS_01_F","GBU12BombLauncher","GBU12BombLauncher_Plane_Fighter_03_F","GMG_20mm","GMG_40mm","HandGunBase","HMG_01","HMG_127","HMG_127_APC","HMG_127_MBT","HMG_127_UGV","HMG_M2","HMG_NSVT","HMG_static","Integrated_NVG_F","Integrated_NVG_TI_0_F","Integrated_NVG_TI_1_F","ItemCompass","ItemGPS","ItemMap","ItemRadio","ItemWatch","Laserdesignator","Laserdesignator_mounted","Laserdesignator_pilotCamera","LMG_65mm_body","LMG_coax","LMG_M200","LMG_M200_body","LMG_Minigun","LMG_Minigun2","LMG_Minigun_heli","LMG_Minigun_Transport","LMG_Minigun_Transport2","LMG_RCWS","M134_minigun","M2","MineDetector","MiniCarHorn","Missile_AA_03_Plane_CAS_02_F","Missile_AA_04_Plane_CAS_01_F","Missile_AGM_01_Plane_CAS_02_F","Missile_AGM_02_Plane_CAS_01_F","MissileLauncher","missiles_ASRAAM","missiles_DAGR","missiles_DAR","missiles_SCALPEL","missiles_titan","missiles_titan_static","missiles_Zephyr","Mk82BombLauncher","mortar_155mm_AMOS","mortar_82mm","NVGoggles","NVGoggles_INDEP","NVGoggles_OPFOR","Put","Rangefinder","Rifle","Rocket_03_AP_Plane_CAS_02_F","Rocket_03_HE_Plane_CAS_02_F","Rocket_04_AP_Plane_CAS_01_F","Rocket_04_HE_Plane_CAS_01_F","RocketPods","rockets_230mm_GAT","rockets_Skyfire","SEARCHLIGHT","SmokeLauncher","SportCarHorn","Throw","TruckHorn","TruckHorn2","TruckHorn3","Twin_Cannon_20mm",
						
									"launch_NLAW_F",
									"launch_RPG32_F",
									"launch_RPG7_F",
									"launch_I_Titan_F",
									"launch_O_Titan_F",
									"launch_B_Titan_F",
									"launch_O_Titan_short_F",
									"launch_I_Titan_short_F",
									"launch_B_Titan_short_F",
									"launch_RPG32_F",
									"launch_NLAW_F",
									"launch_B_Titan_short_F",
									"hgun_Pistol_01_F",
									"srifle_DMR_01_F", 
									"srifle_EBR_F", 
									"srifle_GM6_F", 
									"srifle_LRR_F", 
									"LMG_Mk200_F", 
									"LMG_Zafir_F", 
									"hgun_ACPC2_F", 
									"hgun_P07_F", 
									"hgun_Pistol_heavy_01_F", 
									"hgun_Pistol_heavy_02_F", 
									"hgun_Rook40_F", 
									"arifle_Katiba_F", 
									"arifle_Katiba_C_F", 
									"arifle_Katiba_GL_F", 
									"arifle_Mk20_F", 
									"arifle_Mk20_plain_F", 
									"arifle_Mk20C_F", 
									"arifle_Mk20C_plain_F", 
									"arifle_Mk20_GL_F", 
									"arifle_Mk20_GL_plain_F", 
									"arifle_MXC_F", 
									"arifle_MX_F", 
									"arifle_MX_GL_F", 
									"arifle_MX_SW_F", 
									"arifle_MXM_F", 
									"arifle_MXC_Black_F", 
									"arifle_MX_Black_F", 
									"arifle_MX_GL_Black_F", 
									"arifle_MX_SW_Black_F", 
									"arifle_MXM_Black_F", 
									"arifle_TRG21_F", 
									"arifle_TRG20_F", 
									"arifle_TRG21_GL_F",
									"hgun_PDW2000_F", 
									"SMG_01_F", 
									"SMG_02_F", 
									"srifle_DMR_02_F", 
									"srifle_DMR_02_camo_F", 
									"srifle_DMR_02_sniper_F", 
									"srifle_DMR_03_F", 
									"srifle_DMR_03_khaki_F", 
									"srifle_DMR_03_tan_F", 
									"srifle_DMR_03_multicam_F", 
									"srifle_DMR_03_woodland_F", 
									"srifle_DMR_04_F", 
									"srifle_DMR_04_Tan_F", 
									"srifle_DMR_05_blk_F", 
									"srifle_DMR_05_hex_F", 
									"srifle_DMR_05_tan_f", 
									"srifle_DMR_06_camo_F", 
									"srifle_DMR_06_olive_F",
									"LMG_Mk200_BI_F", 
									"MMG_01_hex_F", 
									"MMG_01_tan_F", 
									"MMG_02_camo_F", 
									"MMG_02_black_F", 
									"MMG_02_sand_F", 
									"arifle_MX_khk_F", 
									"arifle_MX_GL_khk_F", 
									"arifle_MX_SW_khk_F", 
									"arifle_MXC_khk_F", 
									"arifle_MXM_khk_F", 
									"srifle_LRR_tna_F", 
									"srifle_GM6_ghex_F", 
									"launch_RPG32_ghex_F", 
									"launch_B_Titan_tna_F", 
									"launch_B_Titan_short_tna_F", 
									"launch_O_Titan_ghex_F", 
									"launch_O_Titan_short_ghex_F", 
									"srifle_DMR_07_blk_F", 
									"srifle_DMR_07_hex_F", 
									"srifle_DMR_07_ghex_F", 
									"srifle_DMR_07_blk_DMS_F", 
									"hgun_Pistol_01_F", 
									"LMG_03_F",
									"arifle_AK12_F", 
									"arifle_AK12_GL_F", 
									"arifle_AKM_F", 
			
									"arifle_AKM_FL_F", 
									"arifle_AKS_F", 
									"arifle_ARX_blk_F", 
									"arifle_ARX_ghex_F", 
									"arifle_ARX_hex_F", 
									"arifle_CTAR_blk_F", 
									"arifle_CTAR_hex_F", 
									"arifle_CTAR_ghex_F",
									"arifle_CTAR_GL_blk_F",
									"arifle_CTAR_GL_hex_F",
									"arifle_CTAR_GL_ghex_F",
									"arifle_CTARS_blk_F", 
									"arifle_CTARS_hex_F", 
									"arifle_CTARS_ghex_F", 
									"arifle_SPAR_01_blk_F",
									"arifle_SPAR_01_khk_F",
									"arifle_SPAR_01_snd_F",
									"arifle_SPAR_01_GL_blk_F",
									"arifle_SPAR_01_GL_khk_F",
									"arifle_SPAR_01_GL_snd_F",
									"arifle_SPAR_02_blk_F", 
									"arifle_SPAR_02_khk_F", 
									"arifle_SPAR_02_snd_F", 
									"arifle_SPAR_03_blk_F", 
									"arifle_SPAR_03_khk_F", 
									"SMG_05_F",
									"RPG7_F",
									
									"V_DeckCrew_blue_F",
									"V_DeckCrew_green_F",
									"V_DeckCrew_red_F",
									"V_DeckCrew_violet_F",
									"V_DeckCrew_white_F",
									"V_DeckCrew_yellow_F",
									"V_TacVestIR_blk",

//---------------------------------- Uniforms, Vests -------------------------------------

			"B_spotter_F",
			"B_sniper_F",
			"B_Helipilot_F",
			"B_helicrew_F",
			"B_UAV_AI",
			"B_T_Helicrew_F",
			"B_T_Helipilot_F",
			"B_Deck_Crew_F",
			"B_diver_F",
			"B_diver_TL_F",
			"B_diver_exp_F",
			"B_T_Diver_F",
			"B_T_Diver_Exp_F",
			"B_T_Diver_TL_F",
			"O_spotter_F",
			"O_sniper_F",
			"O_helipilot_F",
			"O_Pilot_F",
			"O_helicrew_F",
			"O_UAV_AI",
			"I_UAV_AI",
			"O_T_Helicrew_F",
			"O_T_Helipilot_F",
			"O_T_Pilot_F",
			"O_Fighter_Pilot_F",
			"O_diver_F",
			"O_diver_TL_F",
			"O_diver_exp_F",
			"O_T_Diver_F",
			"O_T_Diver_Exp_F",
			"O_T_Diver_TL_F",
			"C_man_polo_1_F",
			"C_man_polo_1_F_afro",
			"C_man_polo_1_F_euro",
			"C_man_polo_1_F_asia",
			"C_man_polo_2_F",
			"C_man_polo_2_F_afro",
			"C_man_polo_2_F_euro",
			"C_man_polo_2_F_asia",
			"C_man_1",
			"C_man_polo_3_F",
			"C_man_polo_3_F_afro",
			"C_man_polo_3_F_euro",
			"C_man_polo_3_F_asia",
			"C_man_polo_4_F",
			"C_man_polo_4_F_afro",
			"C_man_polo_4_F_euro",
			"C_man_polo_4_F_asia",
			"C_man_polo_5_F",
			"C_man_polo_5_F_afro",
			"C_man_polo_5_F_euro",
			"C_man_polo_5_F_asia",
			"C_man_polo_6_F",
			"C_man_polo_6_F_afro",
			"C_man_polo_6_F_euro",
			"C_man_polo_6_F_asia",
			"C_man_1_1_F",
			"C_man_1_2_F",
			"C_man_1_3_F",
			"C_Nikos",
			"C_Orestes",
			"B_Pilot_F",
			"O_crew_F",
			"g",
			"O_recon_LAT_F",
			"O_recon_medic_F",
			"O_recon_exp_F",
			"O_recon_JTAC_F",
			"O_recon_TL_F",
			"O_Pathfinder_F",
			"O_officer_F",
			"I_Soldier_AAR_F",
			"I_Soldier_AAT_F",
			"I_Soldier_AAA_F",
			"I_support_MG_F",
			"I_support_GMG_F",
			"I_support_Mort_F",
			"I_support_AMG_F",
			"I_support_AMort_F",
			"I_Soldier_lite_F",
			"I_Soldier_A_F",
			"I_Soldier_AR_F",
			"I_Soldier_SL_F",
			"I_Soldier_AA_F",
			"I_medic_F",
			"I_Soldier_exp_F",
			"I_pilot_F",
			"I_Fighter_Pilot_F",
			"I_helipilot_F",
			"I_helicrew_F",
			"I_Spotter_F",
			"I_Sniper_F",
			"I_officer_F",
			"I_Story_Colonel_F",
			"I_diver_F",
			"I_diver_exp_F",
			"I_diver_TL_F",
			"I_G_Soldier_F",
			"I_G_Soldier_lite_F",
			"I_G_Soldier_A_F",
			"I_G_Soldier_unarmed_F",
			"I_G_Survivor_F",
			"I_G_Soldier_universal_F",
			"I_G_Soldier_AR_F",
			"I_G_Soldier_exp_F",
			"I_G_engineer_F",
			"I_G_medic_F",
			"I_G_Soldier_GL_F",
			"I_G_officer_F",
			"I_G_Soldier_M_F",
			"I_G_Soldier_SL_F",
			"I_G_Soldier_TL_F",
			"I_G_Sharpshooter_F",
			"B_G_Soldier_F",
			"B_G_Soldier_lite_F",
			"B_G_Soldier_A_F",
			"B_G_Soldier_unarmed_F",
			"B_G_Survivor_F",
			"B_G_Soldier_universal_F",
			"I_G_Story_SF_Captain_F",
			"I_G_resistanceCommander_F",
			"B_G_Soldier_AR_F",
			"B_G_Soldier_exp_F",
			"B_G_engineer_F",
			"B_G_Soldier_TL_F",
			"B_G_Sharpshooter_F",
			"O_G_Soldier_F",
			"O_G_Soldier_lite_F",
			"O_G_Soldier_A_F",
			"O_G_Soldier_unarmed_F",
			"O_G_Survivor_F",
			"O_G_Soldier_universal_F",
			"O_G_Soldier_AR_F",
			"O_G_Soldier_exp_F",
			"O_G_engineer_F",
			"O_G_medic_F",
			"O_G_Soldier_GL_F",
			"O_G_officer_F",
			"O_G_Soldier_M_F",
			"O_G_Soldier_SL_F",
			"O_G_Soldier_TL_F",
			"O_G_Sharpshooter_F",
			"C_man_p_fugitive_F",
			"C_man_p_fugitive_F_afro",
			"C_man_p_fugitive_F_euro",
			"C_man_p_fugitive_F_asia",
			"C_man_p_beggar_F",
			"C_man_p_beggar_F_afro",
			"C_man_p_beggar_F_euro",
			"C_man_p_beggar_F_asia",
			"C_man_w_worker_F",
			"C_man_pilot_F",
			"C_man_hunter_1_F",
			"C_man_p_shorts_1_F",
			"C_man_p_shorts_1_F_afro",
			"C_man_p_shorts_1_F_euro",
			"C_man_p_shorts_1_F_asia",
			"C_man_shorts_1_F",
			"C_man_shorts_1_F_afro",
			"C_man_shorts_1_F_euro",
			"C_man_shorts_1_F_asia",
			"C_man_shorts_2_F",
			"C_man_shorts_2_F_afro",
			"C_man_shorts_2_F_euro",
			"C_man_shorts_2_F_asia",
			"C_man_shorts_3_F",
			"C_man_shorts_3_F_afro",
			"C_man_shorts_3_F_euro",
			"C_man_shorts_3_F_asia",
			"C_man_shorts_4_F",
			"C_man_shorts_4_F_afro",
			"C_man_shorts_4_F_euro",
			"C_man_shorts_4_F_asia",
			"B_CTRG_soldier_GL_LAT_F",
			"B_CTRG_Sharphooter_F",
			"B_Story_SF_Captain_F",
			"B_CTRG_soldier_engineer_exp_F",
			"B_CTRG_soldier_AR_A_F",
			"b_soldier_survival_F",
			"I_G_Story_Protagonist_F",
			"C_journalist_F",
			"C_scientist_F",
			"C_Nikos_aged",
			"B_Protagonist_VR_F",
			"O_Protagonist_VR_F",
			"I_Protagonist_VR_F",
			"I_G_Soldier_LAT_F",
			"B_G_Soldier_LAT_F",
			"O_G_Soldier_LAT_F",
			"C_Driver_1_F",
			"C_Driver_1_random_base_F",
			"C_Driver_2_F",
			"C_Driver_3_F",
			"C_Driver_4_F",
			"C_Marshal_F",
			"C_Driver_1_black_F",
			"C_Driver_1_blue_F",
			"C_Driver_1_green_F",
			"C_Driver_1_red_F",
			"C_Driver_1_white_F",
			"C_Driver_1_yellow_F",
			"C_Driver_1_orange_F",
			"B_ghillie_lsh_F",
			"B_ghillie_sard_F",
			"B_ghillie_ard_F",
			"O_ghillie_lsh_F",
			"O_ghillie_sard_F",
			"O_ghillie_ard_F",
			"I_ghillie_lsh_F",
			"I_ghillie_sard_F",
			"I_ghillie_ard_F",
			"B_RangeMaster_F",
			"B_Competitor_F",
			"B_G_Soldier_M_F",
			"O_Soldier_lite_F",
			"B_Soldier_lite_F",
			"B_crew_F",
			"B_officer_F",
			"I_C_Soldier_Bandit_7_F",
			"B_soldier_AR_F",
			"B_soldier_LAT_F",
			"B_Patrol_Soldier_AR_F",
			"B_Patrol_HeavyGunner_F",
			"B_Patrol_Soldier_A_F",
			"B_Soldier_GL_F",
			"B_Soldier_SL_F",
			"B_Soldier_TL_F",
			"B_Patrol_Soldier_TL_F",
			"B_Patrol_Engineer_F",
			"B_medic_F",
			"B_soldier_PG_F",
			"B_soldier_UAV_F",
			"B_Patrol_Medic_F",
			"O_soldier_UAV_F",
			"O_Soldier_GL_F",
			"O_Soldier_TL_F",
			"O_soldierU_TL_F",
			"O_SoldierU_GL_F",
			"I_soldier_F",
			"I_Soldier_M_F",
			"I_engineer_F",
			"I_Soldier_universal_F",
			"I_Soldier_unarmed_F",
			"I_Soldier_LAT_F",
			"I_Soldier_AT_F",
			"I_soldier_UAV_F",
			"I_Soldier_GL_F",
			"I_Soldier_TL_F",
			"B_CTRG_Soldier_Exp_tna_F",
			"B_CTRG_Soldier_JTAC_tna_F",
			"B_Story_Protagonist_F",
			"B_CTRG_soldier_M_medic_F",
			"I_G_resistanceLeader_F",
			"B_recon_medic_F",
			"B_soldier_AAR_F",
			"B_soldier_AAT_F",
			"B_soldier_AAA_F",
			"B_support_MG_F",
			"B_support_GMG_F",
			"B_support_Mort_F",
			"B_support_AMG_F",
			"B_support_AMort_F",
			"B_recon_exp_F",
			"B_recon_M_F",
			"B_recon_LAT_F",
			"B_soldier_exp_F",
			"I_Soldier_repair_F",
			"B_soldier_M_F",
			"B_Soldier_A_F",
			"B_engineer_F",
			"B_G_medic_F",
			"I_crew_F",
			"B_T_Pilot_F",
	
			"B_Fighter_Pilot_F",
	
			"V_Rangemaster_belt",
			"V_BandollierB_khk",
			"V_BandollierB_cbr",
			"V_BandollierB_rgr",
			"V_BandollierB_blk",
			"V_BandollierB_oli",
			"V_PlateCarrier1_rgr",
			"V_PlateCarrier2_rgr",
			"V_PlateCarrier2_blk",
			"V_PlateCarrier3_rgr",
			"V_PlateCarrierGL_rgr",
			"V_PlateCarrierGL_blk",
			"V_PlateCarrierGL_mtp",
			"V_PlateCarrier1_blk",
			"V_PlateCarrierSpec_rgr",
			"V_PlateCarrierSpec_blk",
			"V_PlateCarrierSpec_mtp",
			"V_Chestrig_khk",
			"V_Chestrig_rgr",
			"V_Chestrig_blk",
			"V_Chestrig_oli",
			"V_TacVest_khk",
			"V_TacVest_brn",
			"V_TacVest_oli",
			"V_TacVest_blk",
			"V_TacVest_camo",
			"V_TacVest_blk_POLICE",
			"V_TacVestIR_blk",
			"V_TacVestCamo_khk",
			"V_HarnessO_brn",
			"V_HarnessOGL_brn",
			"V_HarnessO_gry",
			"V_HarnessOGL_gry",
			"V_HarnessOSpec_brn",
			"V_HarnessOSpec_gry",
			"V_PlateCarrierIA1_dgtl",
			"V_PlateCarrierIA2_dgtl",
			"V_PlateCarrierIAGL_dgtl",
			"V_PlateCarrierIAGL_oli",
			"V_RebreatherB",
			"V_RebreatherIR",
			"V_RebreatherIA",
			"V_PlateCarrier_Kerry",
			"V_PlateCarrierL_CTRG",
			"V_PlateCarrierH_CTRG",
			"V_I_G_resistanceLeader_F",
			"V_Press_F",
			"H_HelmetB",
			"H_HelmetB_camo",
			"H_HelmetB_paint",
			"H_HelmetB_light",
			"H_Booniehat_khk",
			"H_Booniehat_oli",
			"H_Booniehat_indp",
			"H_Booniehat_mcamo",
			"H_Booniehat_grn",
			"H_Booniehat_tan",
			"H_Booniehat_dirty",
			"H_Booniehat_dgtl",
			"H_Booniehat_khk_hs",
			"H_HelmetB_plain_mcamo",
			"H_HelmetB_plain_blk",
			"H_HelmetSpecB",
			"H_HelmetSpecB_paint1",
			"H_HelmetSpecB_paint2",
			"H_HelmetSpecB_blk",
			"H_HelmetSpecB_snakeskin",
			"H_HelmetSpecB_sand",
			"H_HelmetIA",
			"H_HelmetIA_net",
			"H_HelmetIA_camo",
			"H_Helmet_Kerry",
			"H_HelmetB_grass",
			"H_HelmetB_snakeskin",
			"H_HelmetB_desert",
			"H_HelmetB_black",
			"H_HelmetB_sand",
			"H_Cap_red",
			"H_Cap_blu",
			"H_Cap_oli",
			"H_Cap_headphones",
			"H_Cap_tan",
			"H_Cap_blk",
			"H_Cap_blk_CMMG",
			"H_Cap_brn_SPECOPS",
			"H_Cap_tan_specops_US",
			"H_Cap_khaki_specops_UK",
			"H_Cap_grn",
			"H_Cap_grn_BI",
			"H_Cap_blk_Raven",
			"H_Cap_blk_ION",
			"H_Cap_oli_hs",
			"H_Cap_press",
			"H_Cap_usblack",
			"H_Cap_surfer",
			"H_Cap_police",
			"H_HelmetCrew_B",
			"H_HelmetCrew_O",
			"H_HelmetCrew_I",
			"H_PilotHelmetFighter_B",
			"H_PilotHelmetFighter_O",
			"H_PilotHelmetFighter_I",
			"H_PilotHelmetHeli_B",
			"H_PilotHelmetHeli_O",
			"H_PilotHelmetHeli_I",
			"H_CrewHelmetHeli_B",
			"H_CrewHelmetHeli_O",
			"H_CrewHelmetHeli_I",
			"H_HelmetO_ocamo",
			"H_HelmetLeaderO_ocamo",
			"H_MilCap_ocamo",
			"H_MilCap_mcamo",
			"H_MilCap_oucamo",
			"H_MilCap_rucamo",
			"H_MilCap_gry",
			"H_MilCap_dgtl",
			"H_MilCap_blue",
			"H_HelmetB_light_grass",
			"H_HelmetB_light_snakeskin",
			"H_HelmetB_light_desert",
			"H_HelmetB_light_black",
			"H_HelmetB_light_sand",
			"H_BandMask_blk",
			"H_BandMask_khk",
			"H_BandMask_reaper",
			"H_BandMask_demon",
			"H_HelmetO_oucamo",
			"H_HelmetLeaderO_oucamo",
			"H_HelmetSpecO_ocamo",
			"H_HelmetSpecO_blk",
			"H_Bandanna_surfer",
			"H_Bandanna_khk",
			"H_Bandanna_khk_hs",
			"H_Bandanna_cbr",
			"H_Bandanna_sgg",
			"H_Bandanna_sand",
			"H_Bandanna_surfer_blk",
			"H_Bandanna_surfer_grn",
			"H_Bandanna_gry",
			"H_Bandanna_blu",
			"H_Bandanna_camo",
			"H_Bandanna_mcamo",
			"H_Shemag_khk",
			"H_Shemag_tan",
			"H_Shemag_olive",
			"H_Shemag_olive_hs",
			"H_ShemagOpen_khk",
			"H_ShemagOpen_tan",
			"H_Beret_blk",
			"H_Beret_blk_POLICE",
			"H_Beret_red",
			"H_Beret_grn",
			"H_Beret_grn_SF",
			"H_Beret_brn_SF",
			"H_Beret_ocamo",
			"H_Beret_02",
			"H_Beret_Colonel",
			"H_Watchcap_blk",
			"H_Watchcap_cbr",
			"H_Watchcap_khk",
			"H_Watchcap_camo",
			"H_Watchcap_sgg",
			"H_TurbanO_blk",
			"H_StrawHat",
			"H_StrawHat_dark",
			"H_Hat_blue",
			"H_Hat_brown",
			"H_Hat_camo",
			"H_Hat_grey",
			"H_Hat_checker",
			"H_Hat_tan",
			"H_RacingHelmet_1_F",
			"H_RacingHelmet_2_F",
			"H_RacingHelmet_3_F",
			"H_RacingHelmet_4_F",
			"H_RacingHelmet_1_black_F",
			"H_RacingHelmet_1_blue_F",
			"H_RacingHelmet_1_green_F",
			"H_RacingHelmet_1_red_F",
			"H_RacingHelmet_1_white_F",
			"H_RacingHelmet_1_yellow_F",
			"H_RacingHelmet_1_orange_F",
			"H_Cap_marshal",
			"U_VirtualMan_F",
			"U_B_T_Soldier_F",
			"U_B_T_Soldier_AR_F",
			"U_B_T_Soldier_SL_F",
			"U_B_T_Sniper_F",
			"U_B_T_FullGhillie_tna_F",
			"U_B_CTRG_Soldier_F",
			"U_B_CTRG_Soldier_2_F",
			"U_B_CTRG_Soldier_3_F",
			"U_B_GEN_Soldier_F",
			"U_B_GEN_Commander_F",
			"U_O_T_Soldier_F",
			"U_O_T_Officer_F",
			"U_O_T_Sniper_F",
			"U_O_T_FullGhillie_tna_F",
			"U_O_V_Soldier_Viper_F",
			"U_O_V_Soldier_Viper_hex_F",
			"U_I_C_Soldier_Para_1_F",
			"U_I_C_Soldier_Para_2_F",
			"U_I_C_Soldier_Para_3_F",
			"U_I_C_Soldier_Para_4_F",
			"U_I_C_Soldier_Para_5_F",
			"U_I_C_Soldier_Bandit_1_F",
			"U_I_C_Soldier_Bandit_2_F",
			"U_I_C_Soldier_Bandit_3_F",
			"U_I_C_Soldier_Bandit_4_F",
			"U_I_C_Soldier_Bandit_5_F",
			"U_I_C_Soldier_Camo_F",
			"U_C_man_sport_1_F",
			"U_C_man_sport_2_F",
			"U_C_man_sport_3_F",
			"U_C_Man_casual_1_F",
			"U_C_Man_casual_2_F",
			"U_C_Man_casual_3_F",
			"U_C_Man_casual_4_F",
			"U_C_Man_casual_5_F",
			"U_C_Man_casual_6_F",
			"U_B_CTRG_Soldier_urb_1_F",
			"U_B_CTRG_Soldier_urb_2_F",
			"U_B_CTRG_Soldier_urb_3_F",
			"H_Helmet_Skate",
			"H_HelmetB_TI_tna_F",
			"H_HelmetO_ViperSP_hex_F",
			"H_HelmetO_ViperSP_ghex_F",
			"H_HelmetB_tna_F",
			"H_HelmetB_Enh_tna_F",
			"H_HelmetB_Light_tna_F",
			"H_HelmetSpecO_ghex_F",
			"H_HelmetLeaderO_ghex_F",
			"H_HelmetO_ghex_F",
			"H_HelmetCrew_O_ghex_F",
			"H_MilCap_tna_F",
			"H_MilCap_ghex_F",
			"H_Booniehat_tna_F",
			"H_Beret_gen_F",
			"H_MilCap_gen_F",
			"H_Cap_oli_Syndikat_F",
			"H_Cap_tan_Syndikat_F",
			"H_Cap_blk_Syndikat_F",
			"H_Cap_grn_Syndikat_F",
			"V_TacChestrig_grn_F",
			"V_TacChestrig_oli_F",
			"V_TacChestrig_cbr_F",
			"V_PlateCarrier1_tna_F",
			"V_PlateCarrier2_tna_F",
			"V_PlateCarrierSpec_tna_F",
			"V_PlateCarrierGL_tna_F",
			"V_HarnessO_ghex_F",
			"V_HarnessOGL_ghex_F",
			"V_BandollierB_ghex_F",
			"V_TacVest_gen_F",
			"V_PlateCarrier1_rgr_noflag_F",
			"V_PlateCarrier2_rgr_noflag_F",
			"V_DeckCrew_yellow_F",
			"V_DeckCrew_blue_F",
			"V_DeckCrew_green_F",
			"V_DeckCrew_red_F",
			"V_DeckCrew_white_F",
			"V_DeckCrew_brown_F",
			"V_DeckCrew_violet_F",
									
									
									"U_B_CTRG_Soldier_urb_3_F"
									
									
									
									
						};
						magazines[] = {};
						version = "V1.0";
						author = "kOepi";
			};
};


class CfgWeapons
{

class Default;
	class MGunCore;
	class CannonCore;
	class LauncherCore;
	class DetectorCore;
	class ItemCore: Default {};
	class Uniform_Base: ItemCore {};
	class MGun: MGunCore {};
	class M2: MGun {};
	class LMG_RCWS: MGun {};
	class LMG_65mm_body: LMG_RCWS {};
	class LMG_M200: LMG_RCWS {};
	class LMG_M200_body: LMG_M200 {};
	class LMG_Minigun: LMG_RCWS {};
	class LMG_Minigun_heli: LMG_Minigun {};
	class HMG_127: LMG_RCWS {};
	class HMG_127_APC: HMG_127 {};
	class HMG_127_UGV: HMG_127 {};
	class HMG_01: HMG_127 {};
	class HMG_static: HMG_01 {};
	class HMG_M2: HMG_01 {};
	class HMG_NSVT: HMG_127 {};
	class SmokeLauncher: MGun {};
	class FlareLauncher: SmokeLauncher {};
	class CMFlareLauncher: SmokeLauncher {};
	class CMFlareLauncher_Singles: CMFlareLauncher {};
	class CMFlareLauncher_Triples: CMFlareLauncher {};
	class M134_minigun: MGunCore {};
	class mortar_82mm: CannonCore {};
	class MissileLauncher: LauncherCore {};
	class GMG_F: MGun {};
	class GMG_20mm: GMG_F {};
	class GMG_40mm: GMG_F {};
	class autocannon_Base_F: CannonCore {};
	class autocannon_40mm_CTWS: autocannon_Base_F {};
	class autocannon_30mm_CTWS: autocannon_Base_F {};
	class gatling_20mm: CannonCore {};
	class gatling_30mm_base: CannonCore {};
	class gatling_30mm: gatling_30mm_base {};
	class missiles_ASRAAM: MissileLauncher {};
	class missiles_titan: MissileLauncher {};
	class LMG_Minigun2: LMG_Minigun {};
	class LMG_Minigun_Transport: LMG_Minigun {};
	class LMG_Minigun_Transport2: LMG_Minigun_Transport {};
	class SEARCHLIGHT: MGun {};
	class cannon_120mm: CannonCore {};
	class cannon_125mm: CannonCore {};
	class cannon_105mm: CannonCore {};
	class gatling_25mm: CannonCore {};
	class autocannon_35mm: CannonCore {};
	class mortar_155mm_AMOS: CannonCore {};
	class missiles_Zephyr: MissileLauncher {};
	class missiles_titan_static: missiles_titan {};
	class LMG_coax: LMG_RCWS {};
	class autocannon_30mm: autocannon_30mm_CTWS {};
	class cannon_120mm_long: cannon_120mm {};
	class Twin_Cannon_20mm: gatling_20mm {};
	class Gatling_30mm_Plane_CAS_01_F: CannonCore {};
	class Missile_AGM_02_Plane_CAS_01_F: MissileLauncher {};
	class Cannon_30mm_Plane_CAS_02_F: CannonCore {};
	class HMG_127_MBT: HMG_127_APC {};
	class Launcher: LauncherCore {};
	class Launcher_Base_F: Launcher {};
	class GrenadeCore;
	class GrenadeLauncher: Default {};
	class UGL_F: GrenadeLauncher {};
	class RifleCore: Default{};
	class Rifle: RifleCore {};
	class Rifle_Base_F: Rifle {};
	class Rifle_Short_Base_F: Rifle_Base_F {};
	class Rifle_Long_Base_F: Rifle_Base_F {};
	class HandGunBase: Rifle {};
	class PistolCore: Default{};
	class Pistol: PistolCore {};
	class Pistol_Base_F: Pistol {};
	class Throw: GrenadeLauncher {};
	class Put: Default {};
	class CarHorn: Default {};
	class BikeHorn: CarHorn {};
	class TruckHorn: CarHorn {};
	class TruckHorn2: CarHorn {};
	class TruckHorn3: CarHorn {};
	class SportCarHorn: CarHorn {};
	class MiniCarHorn: CarHorn {};
	class FakeHorn: CarHorn {};
	class ItemWatch: ItemCore {};
	class ItemCompass: ItemCore {};
	class ItemGPS: ItemCore {};
	class ItemRadio: ItemCore {};
	class ItemMap: ItemCore {};

	class MineDetector: DetectorCore {};
	class Binocular: Default {};
	class Rangefinder: Binocular {};
	class NVGoggles: Binocular {};
	class NVGoggles_OPFOR: NVGoggles {};
	class NVGoggles_INDEP: NVGoggles {};
	class Integrated_NVG_F: NVGoggles {};
	class Integrated_NVG_TI_0_F: NVGoggles {};
	class Integrated_NVG_TI_1_F: NVGoggles {};
	
			#include "CfgWeapons.hpp"
			#include "CfgWeaponitems.hpp"
			#include "CfgUniforms.hpp"
			#include "CfgMagazines.hpp"
};
			#include "CfgBackpacks.hpp"